### ISSUE TITLE
Missing Readme

### ISSUE THREAD

**Issue by anilmuppalla** [riaz/Coldwave-OS#1]
Hi Riaz, 

I wanted to use your microkernel. I you can write a Readme file it would be great

**Comment by riaz** [comment]
I very sorry for the inconvenience. I will try to upload it in a day time.

I recommend you to install DJGPP for windows prior, along with the most necessary packages.(Necessary for the build process/ to run the build.bat)

You may also have a look into build.bat which is like a make file in this project.And, I see that i have also included the *.img image of the OS, so you can run it on a virtual machine for testing.

Regards,
Riaz.

**Comment by anilmuppalla** [comment]
I followed you post from [Quora](http://www.quora.com/Linux-from-Scratch/How-long-does-it-take-to-build-a-linux-distro-using-Linux-From-Scratch-LFS-Can-the-distro-developed-by-me-used-for-purposes-similar-to-pre-existing-linux-distro-like-ubuntu/answer/Riaz-Munshi?__snids__=174470712&__nsrc__=2).  This is a Linux based OS isn't it? I am experimenting with LFS and wanted a primer to start with.

**Comment by riaz** [comment]
No, its not a linux-based OS, its a custom OS that has nothing to do with Linux,also my OS has a microkernel while Linux has a monolithic kernel like Windows etc.You can start with LFS right away, with good UNIX skills being the only prerequisite.
